######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
prefer fitenhance=true fitenhancenear=13.2531 fitenhancefar=-13.2531
ribbon display=ribbonsonly
hbondcriteria display=true displayhbond=true displayhalogen=true distance=2.8 donorangle=120 acceptorangle=90 halogendistance=3.5 donorminimumangleasdonor=140 acceptorminimumangleasdonor=90 donorminimumangleasacceptor=120 acceptorminimumangleasacceptor=90 acceptormaximumangleasacceptor=170
displayhbondsmode  mode=all
hbondset2 
hbondset1 all
contactcriteria display=false displaygood=false displaybad=true displayugly=true good=1.3 bad=0.89 ugly=0.75 excludehbond=true
displaycontactsmode  mode=ligandreceptor
contactset2 (protein_near_ligand) or (water)
contactset1 (ligand) or (water)
displaypiinteractions display=false displaystacking=true displaycation=true
displaypiinteractionsmode  mode=ligandreceptor
piinteractionset2 (protein_near_ligand) or (water)
piinteractionset1 (ligand) or (water)
angle 1579 1580 1547 xoffset=0 yoffset=0
angle 1333 1334 1310 xoffset=0 yoffset=0
angle 748 749 737 xoffset=0 yoffset=0
angle 639 640 607 xoffset=0 yoffset=0
angle 741 742 714 xoffset=0 yoffset=0
angle 1302 1303 1287 xoffset=0 yoffset=0
angle 1548 1549 367 xoffset=0 yoffset=0
angle 1764 1765 1734 xoffset=0 yoffset=0
clip front=25.1264 back=-19.8465 frontsurface=10.072 backsurface=-4.79213 leftsurface=64.1325 rightsurface=10.7005 leftslopesurface=0 rightslopesurface=0 frontselect=10.072 backselect=-4.79213 boxoffset=0 objects=all
