######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
prefer fitenhance=true fitenhancenear=22.9494 fitenhancefar=-22.9494
ribbon display=ribbonsonly
hbondcriteria display=true displayhbond=true displayhalogen=true distance=2.8 donorangle=160 acceptorangle=90 halogendistance=3.5 donorminimumangleasdonor=140 acceptorminimumangleasdonor=90 donorminimumangleasacceptor=120 acceptorminimumangleasacceptor=90 acceptormaximumangleasacceptor=170
displayhbondsmode  mode=all
hbondset2 
hbondset1 all
contactcriteria display=false displaygood=false displaybad=true displayugly=true good=1.3 bad=0.89 ugly=0.75 excludehbond=true
displaycontactsmode  mode=ligandreceptor
contactset2 (protein_near_ligand) or (water)
contactset1 (ligand) or (water)
displaypiinteractions display=false displaystacking=true displaycation=true
displaypiinteractionsmode  mode=ligandreceptor
piinteractionset2 (protein_near_ligand) or (water)
piinteractionset1 (ligand) or (water)
angle 1857 1858 1822 xoffset=0 yoffset=0
angle 1725 1726 1662 xoffset=0 yoffset=0
angle 1565 1566 1540 xoffset=0 yoffset=0
angle 1440 1441 1407 xoffset=0 yoffset=0
angle 1368 1369 1332 xoffset=0 yoffset=0
angle 912 913 895 xoffset=0 yoffset=0
angle 622 623 602 xoffset=0 yoffset=0
angle 462 463 407 xoffset=0 yoffset=0
angle 343 344 297 xoffset=0 yoffset=0
angle 156 157 116 xoffset=0 yoffset=0
angle 146 147 101 xoffset=0 yoffset=0
angle 246 247 204 xoffset=0 yoffset=0
angle 408 409 381 xoffset=0 yoffset=0
angle 534 535 481 xoffset=0 yoffset=0
angle 901 902 772 xoffset=0 yoffset=0
angle 1154 1155 983 xoffset=0 yoffset=0
angle 1418 1419 1383 xoffset=0 yoffset=0
angle 1508 1509 1480 xoffset=0 yoffset=0
angle 1629 1630 546 xoffset=0 yoffset=0
angle 1735 1736 1662 xoffset=0 yoffset=0
clip front=42.4505 back=-86.4886 frontsurface=42.4505 backsurface=-86.4886 leftsurface=-48.6455 rightsurface=80.2935 leftslopesurface=0 rightslopesurface=0 frontselect=42.4505 backselect=-86.4886 boxoffset=0 objects=all
